### ISSUE TITLE
Any Excel file upload of menuitems

### ISSUE THREAD

**Issue by kiranbdesh** [joshsoftware/the_hunger_terminal#116]
We have added functionality to upload CSV file of menu items. But there may be many users who may be using Windows OS. They would be familiar to Excel formats. So we should have functionality  to upload Excel files of menu items. Task :

- [ ] Upload xls, xlsx files for menu items

**Comment by gautamrege** [comment]
There is no need to complicate things. CSV can be edited on any machine.
