### ISSUE TITLE
Download pdf option is not working

### ISSUE THREAD

**Issue by kirandeshmukh** [joshsoftware/the_hunger_terminal#117]
When I clicked on download_pdf option to generate pdf for last month report of employees, I expect to generate pdf of tht report. But I will get blank page as result:
![download_pdf](https://cloud.githubusercontent.com/assets/24954080/26145681/db9d041e-3adc-11e7-9381-464b57d5535e.png)

**Comment by kirandeshmukh** [comment]
This problem has been fixed. But now, we are getting a page: 
![downloadpdf](https://user-images.githubusercontent.com/24954080/28510776-ceda6404-7067-11e7-983e-13fd2b0fa934.png)

Tasks to be performed: 

- [ ] Remove unwanted link for download pdf

- [ ] Remove Unwanted links on emploayee name

- [ ] Remove scrollbar

- [ ] Display  columns - Subsidy, Extra Charges and CTE  on PDF

- [ ] Display copyright information at footer

**Comment by meenakshikumari** [comment]
Seema Ma'am had a requirement that CTE (Cost to Employee) in employee's last month report shoul be rounded up to tens digit. 
For example, if CTE is 62 then it should be rounded to 60. And if CTE is 63 then it should be rounded to 70.

Previous reports is attached here:

![download_pdf_old](https://user-images.githubusercontent.com/9154721/30062586-52b627ea-9269-11e7-9f8b-4e8c01e4f653.png)

After above modification in report , it should look like this: 

![screenshot from 2017-09-05 18 43 03](https://user-images.githubusercontent.com/9154721/30062807-161e07fc-926a-11e7-97e4-ac2a4ae84346.png)
