### ISSUE TITLE
Create README file

### ISSUE THREAD

**Issue by kirandeshmukh** [joshsoftware/the_hunger_terminal#122]
- [ ] Create README file having appropriate badges, featurewise description

- [ ] Include license file

**Comment by gautamrege** [comment]
Please get this done quickly. I will edit it and make the final README version but the first cut should come from you both.

**Comment by kirandeshmukh** [comment]
# Why did we build The Hunger Terminal ? What motivated us?

At Josh Software till last year, a single caterer was present. Most of the times, not all the employees used to like food which resulted in food wastage. So, this platform was created from where employees can easily order their food from registered vendors. Our main motive was to reduce food and water wastage.

# Is your company interested in using The Hunger Terminal ?

If your company wants to support this cause, please contact us at[ info@thehungerterminal.com.](http://info@thehungerterminal.com)
List of companies that are supporting this cause :

- [Josh Software](http://joshsoftware.com)

# What is The Hunger Terminal all about?

Here are some questions that should help you get going. A lot more questions that are answered in the [FAQ](http://thehungerterminal.com/faqs).

## Who should use The Hunger Terminal ?

Corporate companies who wants to reduce food wastage can use this platform for their employees.

## How does it work ?

- Company Admin will sign up by giving company and his/her details along with the ordering time and subsidy given by company (if any).

- Company admin will add local food vendors with their menu.
 

- He/she will send invitation to all the employees of the company.

- Employee who accept the invitation are only allowed to order from the website.

- Employee need to login at the given time interval to place order from registered vendor.

- A reminder will be send to registered employees who have not placed order for that day.

- The monthly employee and vendor reports are generated for company admin.

- Employee can check his/her order history.

# Upcoming features

-  Respective frequently ordered dishes(featured dishes) of each employee will be displayed in the reminder mail.

-  Employee can place his/her order just by clicking the featured dish.

-  Employee can rate to a particular vendor, menu item.

- Employee can set their preferences: Veg or Nonveg.

- Employee will be able to place orders from multiple vendors in a day

**Comment by kirandeshmukh** [comment]
@gautamrege ,
Can you please review the above readme file?

**Comment by gautamrege** [comment]
@kiranbdesh123 please commit this to README.md -- there's no point keeping it in an issue .. I saw this for the first time. I can directly edit the README.

**Comment by kirandeshmukh** [comment]
@gautamrege ,

I will make the required commit.

**Comment by kirandeshmukh** [comment]
Added the required README.md file in the master branch.
