### ISSUE TITLE
Navigation and sidebar modification

### ISSUE THREAD

**Issue by kirandeshmukh** [joshsoftware/the_hunger_terminal#124]
Present view: 
![nav_bar](https://cloud.githubusercontent.com/assets/24954080/26110689/9838a47a-3a42-11e7-8d2b-61b235fd76ab.png)

Modifications:

- [ ] Now, we have two navigation bars: vertical and horizontal. Remove vertical navbar. Add all the navigation links on horizontal bar.

Modified view would look like:
![img_20170516_195536](https://cloud.githubusercontent.com/assets/24954080/26111152/da5dec42-3a43-11e7-888a-5f1c8b442a9c.jpg)

**Comment by gautamrege** [comment]
It would help if you design which menus you are having. My opinion (and please feel free to change this). 

* No sidebar required.
* Horizontal menu should ave the following options
    * Employee: "Place Order", "History", "Logout".
    * Admin Dashboard: http://hunger-terminal.herokuapp.com/reports/all_terminals_daily_report (Restful url: http://hunger-terminal.herokuapp.com/terminals/reports/daily). Also there should be a link to "Extra Charges" on this page.
    * Admin: 
        * "Today" -> "Vendors", "Employees", "Payment"
        * "Reports" -> "Employee Deductions", "Vendor Running Balance"
        * "Settings" -> "Terminals", "Employees", "Discounts"

**Open for discussions**

**Comment by kiranbdesh** [comment]
AS per above suggestion, we may have a navbar like:

![img_20170518_194550](https://cloud.githubusercontent.com/assets/24954080/26206833/5e1143b2-3bd5-11e7-8ca7-e3600f918cee.jpg)

In my opinion, we can implement following things:
1. Employee may have different navbar which contains separate options for "place order", "Order History" and "logout".
2. After clicking on Vendor last month report, we may get vendor running balance for particular
vendor . Here, We may get running balance for a particular period by specifying date range
