### ISSUE TITLE
Study and Apply Database indexing

### ISSUE THREAD

**Issue by kirandeshmukh** [joshsoftware/the_hunger_terminal#126]
Now, It requires 12.6ms for showing order history for an employee, who has  ordered food at max 10 times . 
![screenshot from 2017-05-16 17-19-07](https://cloud.githubusercontent.com/assets/24954080/26113368/e5dd5ade-3a49-11e7-8ef7-d0a385c4ec3e.png)

And this time will increase as the number of records increases. Same is the case for report generation of employees and terminals. To increase the performance, we have to use indexing

Tasks to be completed may include applying indexing while accessing following functionalities:

- [ ] Order history page

- [ ] Employee reports pages

- [ ] Terminal Report pages

- [ ] Current running balances pages

**Comment by gautamrege** [comment]
You are facing the N+1 query problem. Please study this and resolve. Indexing will help but the core of this problem is the the number of queries that are being fired. 
Please state you findings here before you start this work. 

Btw, very well written description! Good.

**Comment by kiranbdesh** [comment]
Our project is facing problem of N+1 queries. The reasons behind it:
1. In order history page, we are loading order_details for each order in loop .  Image showing it:
![n 1problem](https://cloud.githubusercontent.com/assets/24954080/26200902/04d88e3c-3bc0-11e7-8f36-9d9a66db21da.png)


Means if there is parent-child relation between two models, for accessing each child, there will be separate query.

If I have removed this n+1 query problem, we will get all the child records in only one query. Image showing it:

![solnton 1](https://cloud.githubusercontent.com/assets/24954080/26201369/2e73d60a-3bc2-11e7-826a-30d0edced57e.png)


For solving this n+1 queries problem, we can use "includes" clause. It will load all the child records while loading the records of parent. We can replace "joins" with "includes" to get rid of it.

**Comment by gautamrege** [comment]
Good! Par proceed. 

Look at all the slow requests, I.e more than 2 seconds in server logs and figure out how to optimize them. Please note then here.

**Comment by kiranbdesh** [comment]
**Removes unnecessary queries** 

Before:
![11duplicatequeries](https://cloud.githubusercontent.com/assets/24954080/26352703/79bf93f8-3fda-11e7-9204-91b84f2b7719.png)

After:
![12duplicatequeries](https://cloud.githubusercontent.com/assets/24954080/26352745/b3a33c50-3fda-11e7-856b-328b855bc89f.png)

**Remove n+1 problem on Order history page:**

Before:
![1withoutincludeorderhistory](https://cloud.githubusercontent.com/assets/24954080/26352773/de125f34-3fda-11e7-960b-391ec47593dc.png)

After:
![1withincludeorderhistory](https://cloud.githubusercontent.com/assets/24954080/26352783/e76f4a88-3fda-11e7-88ce-2e46365abc42.png)

**Remove n+1 problem on order edit page:**

Before:
![1withoutincludeorderedit](https://cloud.githubusercontent.com/assets/24954080/26352844/2d5f2572-3fdb-11e7-8d51-db220513efa2.png)

After:
![1withincludeorderedit](https://cloud.githubusercontent.com/assets/24954080/26354290/9b3cc008-3fe1-11e7-868e-b4473bcdd645.png)

**Comment by kiranbdesh** [comment]
Production logs for various pages:
1. For **Order history** page:
```
Completed 200 OK in 167ms (Views: 61.2ms | ActiveRecord: 74.8ms)
```

2. For **Order Edit** page:
```
Completed 200 OK in 231ms (Views: 109.9ms | ActiveRecord: 74.1ms)
```

3. For **new order** page where unnecessary queries for counting Veg and Nonveg items are executed:
```
Completed 200 OK in 61ms (Views: 39.3ms | ActiveRecord: 7.3ms)
```
Also, there are queries used while generating reports which needs to be optimized.

**Comment by gautamrege** [comment]
@kirandeshmukh You too have not bothered to read [Git Flavoured markdown](https://guides.github.com/features/mastering-markdown/) I shall get you started 

Records | Before |  After | 
-------- | ------- | ----- |
100 | 587ms | 105ms |
200 | 596ms | 193ms|
500 | 
700 |
1000 |
5000 |

**Comment by kirandeshmukh** [comment]
1.n+1 queries from the project are removed. This is verified with "bullet" gem.

2.Also, There are JOIN queries in used for report generation. And JOINS is better than using loops and having more than one queries.
3. There is need of modifications in current running balances page. We will modify it and will have optimized query

There is the need of removing redundancy in queries and modify some Class methods to Instance methods. This will be done in another issue
