### ISSUE TITLE
CompanyAdmin - Terminal Page

### ISSUE THREAD

**Issue by SakshiParakh** [joshsoftware/the_hunger_terminal#13]
This page contains details of all the terminals and their menuitems

- [ ] listing of terminals with their logo
- [ ] menu listing for each terminal
- [ ] option to add/edit terminals and menu items

![terminal_page](https://cloud.githubusercontent.com/assets/13197140/22585397/a66ee2d6-ea1d-11e6-958c-ceef069436df.JPG)

**Comment by SakshiParakh** [comment]
issue assigned to @imAkshay26

**Comment by imAkshay26** [comment]
todays target:
- [ ]  Options to add delete terminals and menuitems

**Comment by imAkshay26** [comment]
todays goal:
- [ ]  designing of menu item and terminal details form.
- [ ]  designing of showing details of menuitem and its terminal
