### ISSUE TITLE
CompanyAdmin - Employee Page

### ISSUE THREAD

**Issue by SakshiParakh** [joshsoftware/the_hunger_terminal#14]
Listing of all the employees 

- [x] Pagination
- [ ] search on name and mobile number
- [ ] filter to show active employees
- [x] option to update status (i.e active or inactive )
- [ ] Send Invite 

![employee_page](https://cloud.githubusercontent.com/assets/13197140/22585486/0d422e96-ea1e-11e6-8e83-e974e896a78b.JPG)

==================
APPROACH
==================

1. When company admin will login , if he clicked on employees button , he will see all the emplyees in that company
2. While showing the list of emplyees, I will show status(Active/Inactive) with the help of glyphicons(Red and green in color)
3. I will also provide button to update status of that employee
4. We are not providing facility to delete any of the employee record. We will just deactivate that emploee. It will be useful for report generation

5. Company admin can send invitations to employees. Last time, company admin was filling all the details of the emplyee and sending invitations due to validation. I have to study about devise invitable in detail. I will write about it till tomorrow.

**Comment by SakshiParakh** [comment]
issue assigned to @kiranbdesh

**Comment by kiranbdesh** [comment]
?  Ma'am , I think , we should provide facility to update email and mobile number of the employee. What should I do?
? Now we are considering company has one company admin . If company admin is changed, I think, his record should be edited by Super admin. Then what should we do with previously present company admin? Should we maintain a flag ?


Today's Target:
1. Search on name and mobile number
2. Option to update status

**Comment by amitk** [comment]
**Description**
I am implementing devise invitable on the user model.

- first sending invitations to user only through email then after response of user allowing to fill her/his additional details.
- Implementing devise invitable on user model.

**Comment by kiranbdesh** [comment]
Today's Taget:
1.Search on name and email id (I think, instead of search on mobile number, search on email will be real time)
2. Filter to show active employees

**Comment by kiranbdesh** [comment]
Today's Taget:
1.Search on name and email id (I think, instead of search on mobile number, search on email will be real time)
2. Filter to show active employees

**Comment by kiranbdesh** [comment]
ma'am , company admin can see list of  all the employees .  And there itself he can activate / deactivate an employee.Can he see his own record in the list?
 If yes, should he deactivate his own record there?
