### ISSUE TITLE
Writing Test cases

### ISSUE THREAD

**Issue by imAkshay26** [joshsoftware/the_hunger_terminal#142]
- [x] Test cases for all the models and controllers will be written.

- [ ] Now we are using `Minitest-rails , factory girl `for testing. It would be better to switch to `minitest-rails-shoulda`. It will reduce lots of manual coding part.

**Comment by kirandeshmukh** [comment]
Test cases which are written till 3rd July, 2017 are merged in the master. From now onwards, we can write/fix test cases when we are adding a new feature/ fixing a bug.

Hence closing the ticket.
