### ISSUE TITLE
Updated discount is not reflected in order

### ISSUE THREAD

**Issue by kirandeshmukh** [joshsoftware/the_hunger_terminal#163]
If I place an  order when discount is 60 Rs or 60% whichever is lesser --->

![orderbug1](https://user-images.githubusercontent.com/24954080/27625561-a8e069d4-5c02-11e7-96b3-58fa97f0383a.png)

Then Company changed its discount to 55 Rs or 55% . And I want to edit my order --->

![orderbug2](https://user-images.githubusercontent.com/24954080/27625567-ae208140-5c02-11e7-870c-5cc51f8d2b25.png)

After editing, I will get  --->

![orderbug3](https://user-images.githubusercontent.com/24954080/27625572-b137c87a-5c02-11e7-84d1-3e74d3734016.png)

This bug should be fixed.
@gautamrege , which discount should be shown at the time of editing - The one which was at the time of placing the order or updated one?

**Comment by gautamrege** [comment]
I think that any discount that is applied, should be effective the NEXT DAY.
So, for that day, we should not change 60% to 55%.

**Comment by kirandeshmukh** [comment]
For making updated discount from Next Day, we can follow following steps:

- [ ] Save updated discount value in a different field. After setting this field, employees will notification that this will be discount from tomorrow .

- [ ]  Run a rake task everyday at 1 am and if it get this updated value, assign this value to discount field of a company. On Heroku, we can use Heroku Scheduler for running rake task everyday.
