### ISSUE TITLE
General Employee - Order Page

### ISSUE THREAD

**Issue by SakshiParakh** [joshsoftware/the_hunger_terminal#17]
- [ ] tab1 - its order history 
- listing of all previous menu items with their cost
- filter based on date 
- [ ] tab2 - place order 
- show menu items for that day
- option to select multiple menu items
- [ ] tab3 - place order for next day 

![16763820_1184926851616866_798678366_o](https://cloud.githubusercontent.com/assets/16892315/23056672/7aef81c4-f512-11e6-9ffd-fc8cc77c2444.jpg)

**Comment by Shivamkumarsingh** [comment]
Today's Target

1. Designing Order page of the general employee where there are 2 tabs one for order history and other for placing order page which comprises of menu items for that day.

**Comment by Shivamkumarsingh** [comment]
Today's Target

1. To integrate the standalone views to the application by creating dummy controller, assets, and respective views files & routes.

**Comment by Shivamkumarsingh** [comment]
Done with today's task except for auto update of the cart on item selection from the menu.
