### ISSUE TITLE
Add custom validation for uniqueness of  user email in a company

### ISSUE THREAD

**Issue by kirandeshmukh** [joshsoftware/the_hunger_terminal#171]
Company and User has Parent-child relation.Both the models have field called 'email'. 
Company email has uniqueness constraint. 
Also, we have User email uniqueness having scope of  company_id .
 An user record is created at the time of company creation using nested  form. Since both models have same field - 'email', uniqueness on Child(User) email is not working under the scope of company_id .
 It is the problem of nested attributes. So, if we want to apply uniqueness on user email, we should use a custom validation.

**Comment by meenakshikumari** [comment]
Uniqueness validation was not required in email id of user model but it was required for company model (it has been modified).
