### ISSUE TITLE
Add Tax field in order table 

### ISSUE THREAD

**Issue by meenakshikumari** [joshsoftware/the_hunger_terminal#189]
As tax field was not present in orders table therefore a problem was coming. 
For example, a company is providing a subsidy of 50% or ₹50 whichever is less. If user is ordering a paneer dish of ₹80 from vendor having tax of 15% then total payable amount is ₹52. 
As shown in highlighted part in below screenshot:

![screenshot from 2017-08-08 12 59 15](https://user-images.githubusercontent.com/9154721/29060958-8b57b97e-7c39-11e7-8a88-609e1d4e6a7b.png)

But when the order is placed after that in orders show page, the total payable is ₹46.  
As shown in highlighted part in below screenshot:

![screenshot from 2017-08-08 12 58 57](https://user-images.githubusercontent.com/9154721/29060977-9b8d5984-7c39-11e7-923c-879ee26355f7.png)

This problem is coming because from client side we are sending server the total_cost which is summation of cost of dish and tax applied on it. And then on that total_cost the discount is getting calculated which not correct. 
  In the above case the total_cost is ₹92 and the discount calculated is ₹46, so the payable amount is coming ₹46 which is wrong. The correct way is ( cost of dish + tax - discount on cost of dish) i.e. ( ₹80 +
 ₹12 - ₹40 = ₹52 ).

Therefore, we need to add separate tax field in orders table.

**Comment by gautamrege** [comment]
I had told you NOT to do client side calculations for this!! 

You have **everything** on the server-side from database: 
* The price of the dish
* The tax
* The discount 

So, WHHHHHYYYY are we calculating on client side and sending a `total_cost` ???  I remember even explaining this to you! 

This can cause a BIG problem if people simply manipulate the hidden field in HTML and send a different value to server! So, **ALL calculations MUST be done on server side**

**Comment by meenakshikumari** [comment]
Sir, in this issue i'm trying to solve this problem only.

 As in orders table there was no tax field that's why i'm adding it and the calculations which were previously done from client side will be removed and will be done at server side.
