### ISSUE TITLE
Carrierwave

### ISSUE THREAD

**Issue by SakshiParakh** [joshsoftware/the_hunger_terminal#30]
Implementation of carrierwave for

- [ ] Terminal logo
- [ ] MenuItem Image

**Comment by SakshiParakh** [comment]
@MEENIA I don't see any commits from your side. This story was to be complete today ??

**Comment by MEENIA** [comment]
sorry ma'am for being late.
I was trying carrier wave in my old project.I will try to submit it by
tomorrow.

**Comment by SakshiParakh** [comment]
@MEENIA I still dont see any commits here?? Have you finished the task

**Comment by MEENIA** [comment]
Maam I'm still doing it
