### ISSUE TITLE
SuperAdmin - Company and Empolyee Management

### ISSUE THREAD

**Issue by gautamrege** [joshsoftware/the_hunger_terminal#6]
There will be one role SuperAdmin who manages all companies that want to land on the platform.
These features are *only* applicable to SuperAdmin:

- [x] Test Cases
- [x] Company Listing
- [x] Create SuperAdmin role in Users
- [x] Updating CompanyAdmin Details
- [x] Updating Company Details 
- [x] Deleting Companies

Future Scope:
- [x] Add Companies 
- [x] A mandatory CompanyAdmin(type of employee) to be added while adding the company

Model Names: 
 ```Company```
 - name
 - location
 - landline 

```Users```
- name
- role (SuperAdmin/CompanyAdmin/Employee) Note: only one CompanyAdmin per company
- mobile_number
- email_id
- status(Active/ Inactive)

Associations
```ruby
class Company
   has_many :users, as: employees
```

```ruby
class User
   belongs_to :company
```

==========
APPROACH:
==========
1. First, I will create models for Company and Address
2. I will write test cases for these models with the help of Minitest rails, factory girl and Faker
    These test cases will be for various validations applied on the attributes like presence,uniqueness,numericality, length.
3. Also there will be test cases in company since we are going to use dependent : :destroy for address and user
4. Then I will write test cases for company controller.(RUD operations)
5. Then I will write company controller and view for listing the added companies
6. After this task, I will write controller for updating company record. While updating company record, we can also update company admin record . For this, I will use User model created in another model
7. Then , I will write controller for deleting company record.As soon as company record would be deleted, its address record and all the users of that company will also be deleted.

8.After completing  these RUD operations, I will link all these pages so that all the tasks will be done by super admin only.

**Comment by SakshiParakh** [comment]
issue assigned to @kiranbdesh

**Comment by kiranbdesh** [comment]
Is it necessary to have an address for user?

**Comment by kiranbdesh** [comment]
Today's Target:
1. Test cases for company and address model
2. Test cases for company controller(RUD operations)
3.Test cases for User model. This model will be created using devise in another issue

**Comment by kiranbdesh** [comment]
Today's target:
1. All possible test cases for company, address and user model 
2.test cases for company controller(RUD)
3. Use of Simplecov and codeclimate

**Comment by kiranbdesh** [comment]
Today's Target
1. Use of code climate
2.Test cases for company cotroller
3.Test cases for User model

**Comment by kiranbdesh** [comment]
Today's Target:
Test cases for user model

**Comment by SakshiParakh** [comment]
@kiranbdesh 

Your task for today is not up to the mark. Why would it take the whole day to write only test cases for user model??

**Comment by kiranbdesh** [comment]
. In user model, we are providing a Field "role" which would have value "Super Admin", "Company Admin " or "Employee". We will have Company has many Users relation But this will create compulsion that Super admin should have Company ID

Then what should I do? Whether to create separate Admin model ?

**Comment by kiranbdesh** [comment]
Today's target:
1. Company controller(RUD) operations
 a) Use of nested form for company admin and address record
2. Employee listing page [issue no 14]
   a) Pagination (Using Kaminari)
   b) Search using mobile number and name

**Comment by SakshiParakh** [comment]
@kiranbdesh - Pagination ans search are not part of this story
Please complete the tasks specific to this issue first.

**Comment by kiranbdesh** [comment]
Ma'am , I am stuck with "polymorphic" and "has many " relationship while creating associations in factories

**Comment by kiranbdesh** [comment]
Today's target:
1.I have written controller actions for RUD of company. 
There is problem while saving user with company_id . I am trying to fix it.
2. I will start with issue 14

**Comment by SakshiParakh** [comment]
Where is you today's task ? Is this story complete ??

**Comment by SakshiParakh** [comment]
Story completed :ship:
