### ISSUE TITLE
Company(Tenant) Dashboard

### ISSUE THREAD

**Issue by gautamrege** [joshsoftware/the_hunger_terminal#7]
This could be considered as the home page or the company page

- [x] Basic Dashboard layout
- [x] Navigation bar components:
- Home
- About
- Contact 
- [x]  SignUp - of companies along with the company admin
- [x]  SignIn - applicable *only* for employees of that company
- [x]  SignOut

*Basic layout structure images yet to be attached*
![home_page](https://cloud.githubusercontent.com/assets/13197140/22584536/f680a430-ea18-11e6-8037-bc915eadee59.JPG)

![login_page](https://cloud.githubusercontent.com/assets/13197140/22585288/1530f3d6-ea1d-11e6-94d1-8226afdf3bb1.JPG)

Approach:
1.create user model with devise and setup all the configurations required for user(sending mails, adding additional columns like role and status)
2.Add mail interceptor so that all mails are forwarded to a test account
3.Configure devise invitable for adding employees of company
4.creating the dashboard layout(i.e home page) for this application
5.creating the sign up for companies in which details of company and company admin are added i.e a new company is always created with its company admin
6.customizing devise views with bootstrap

**Comment by SakshiParakh** [comment]
issue assigned to @tejaswini-gambhire

**Comment by tejaswini-gambhire** [comment]
Todays task:

1. create user model with devise
2. devise modules that get added by default are rememberable, recoverable, trackable, validatable, database_authenticatable and registerable.
3.as we dont want signup of employees, I will skip registeration but it is necessary to let the employees to edit and update their password if they want so I will add routes for editing and updating password.
4. additional devise modules that I will add are confirmable, lockable and timeoutable.
5.after that I will add the additional fiels in user table such as 
  - mobile_number
  - role
  - status 
6. after that I will add mail configuration in development.rb
7. then I will add development mail interceptor
8. then I will design the basic dashboard layout.

**Comment by tejaswini-gambhire** [comment]
1. adding 'name' field to user
2. instead of 'active' field keeping it as 'is_active'

**Comment by tejaswini-gambhire** [comment]
Today's Task:
I will continue the design of homepage(tenant dashboard).

**Comment by tejaswini-gambhire** [comment]
I have created the homepage as per my understandings. I will focus on the next task today and side by side if I will get any idea to modify the homepage, I will do it.

Today's Task: 
1. To add company signup functionality in the application.
2. For that I will create a nested form which will contain company details as well as company admin         details.

**Comment by SakshiParakh** [comment]
Ok go ahead. But show me the design of the homepage.

**Comment by tejaswini-gambhire** [comment]
should there any validation like one company can have only one company admin.

**Comment by tejaswini-gambhire** [comment]
todays task could not be completed as it was dependent on another issue. the basic signup form for company will be like this:
![company-signup](https://cloud.githubusercontent.com/assets/16642924/22887943/0326a7a2-f22a-11e6-927f-e2b7f3e66a02.jpg)

**Comment by tejaswini-gambhire** [comment]
Today's approach:
1. create a nested form for company signup
2. it will contain nested attributes for address(i.e. company location) and nested attributes for user(i.e. company admin)
3. so instead of location field, form will contain following fields:
    - house no
    - pincode
    - locality
    - city
    - state  
4. when admin will click on sign up three actions will be performed:
    - new company record will be added to company.
    - location of company will be inserted into address table.
    - an email will be sent to company admin for confirming the account.

now I have two doubts in this. 
1.is it necessary to take the address of company at the sign up time?
2.which mail should be sent to company admin? confirmation mail or invitation mail.

**Comment by tejaswini-gambhire** [comment]
completed the company sign up functionality.
address and admin details are getting saved while saving the company.
aligned the company sign up form but it is scrolling a little bit as it is large.

**Comment by SakshiParakh** [comment]
Completed :ship:
