### ISSUE TITLE
Terminal and MenuItem Management

### ISSUE THREAD

**Issue by gautamrege** [joshsoftware/the_hunger_terminal#9]
A Terminal is Food vendor. Each Terminal will have their own menu items. 
We call this a terminal because this is a visual food court!

This feature allows *only* the HR (refs Roles # ) to:

- [x] Test cases
- [x] Add a new terminal 
- [x] Add new menu item of a terminal (nested)
- [x] Import Menu items from a CSV file upload
- [x] Edit the terminal name, logo, contact details. 
- [x] Edit various menu item name, price, availability.
- [x] Delete menu items (note: this should not be part of any current order)
- [x] Delete a vendor (note: this vendor should not be a part of current order and have pending payments)

Model names: ```Terminal``` and ```MenuItem```

Associations: 
```ruby
class Terminal
   has_many :menu_items
```

```ruby
class MenuItem
   belongs_to :terminal
```

Approach:
````
1) Creating model Terminal and MenuItem and writing association for them.
Terminal has many MenuItem and MenuItem belobgs_to Terminal ,Terminal has_one address.
 -Fields for Terminal :-  name:string, landline:string
 -Fields for MenuItem :- name:string,veg:boolean,price:integer
2) Writing test cases for Models Terminal and MenuItem. 
  -Test Cases for terminal: test case will be created using minitest,faker,factory girl.
  -name should not blank,name should be unique,if two names differ in case sensitivity
    but it should added in only one record.
 -landline number should in this format 22-12345624. so only numeric and 
  hyphen accepted and  length =11
3)Generating Controller for Terminal and MenuItem.
  Function:-Adding new terminals with their menu items nested.For creation
 of new terminalwe can take information of terminal using simple form.on 
 clicking add menuitem pop up should open where we can add 
 nested menu items.

4) testing terminal and menuitem actions of new terminal and adding menu items.
5)importing of menuitems from csv file.csv file should read as row by row and each
  one record  should be inserted in database. 
  -Testing csv:csv should not be empty and no of fields in csv and table should same
  excepting serial no in csv file.
6) editing terminal info like name,logo,contact details for that we can use edit action
 when company     admin click on edit button then fetch terminal id at back end and
 render that form and fetch values from database and then company admin update
 that details and update the record. edit action returns html form.so all data fetched
 from db could be taken in simple form or html form.

7)then testing for edit and update action of terminal controller.
8) editiing menuitems will be same as editing terminal details.but i am not sure can
 we update multiple record using edit action and single simple form.

9)and then testing for editing menu items.

10)for the deletion of menu item, when company admin click on menuitem
 for particluar terminal then we will show all menus for that terminal by 
taking object = fetched_object_id_of terminal.menuitems.By using this object
 we will create one view on that we will give checkbox for deleting the menuitems.

11)before destroy callback should be used for checking menuitem is not present
 in the order  table by using menu item id.

12)before destroy call back should be used for checking vendor_id present in order
 table return false if present same do for payment table.if both returns true then
  only delete vendor

**Comment by SakshiParakh** [comment]
issue assigned to @imAkshay26

**Comment by imAkshay26** [comment]
Todays Goal:

- [ ] Creation of models their association. 

- [ ] Validations on models

- [ ] Test cases for models and testing models using minitest,factoy girl and faker

- [ ] Generating of controller for menuitem and terminal.

- [ ]  Generating Resources for menuitem and terminal.

**Comment by imAkshay26** [comment]
today's target 

- [ ] test cases for models using faker,factory girl and minitest

- [ ] Generating controller and routes for resources.

**Comment by imAkshay26** [comment]
Todays Target:
- [ ] generating terminal controller
- [ ] generating resources for terminal
- [ ] all test cases for the terminal controller

**Comment by imAkshay26** [comment]
todays task:
- [ ]  adding menu item  for terminal 
- [ ]  import menu item from csv upload
- [ ]  test cases for above two functions

**Comment by SakshiParakh** [comment]
Did you review your PR changes?

**Comment by imAkshay26** [comment]
Todays goal:
- [ ]  edit the name,contact details of terminal
- [ ]  edit the menu items details
- [ ]  delete the menu items
- [ ]  delete menu items
- [ ]  delete terminal

**Comment by SakshiParakh** [comment]
what about CSV, have you completed that task?

**Comment by imAkshay26** [comment]
we can upload csv file,currently its not reading csv file.It will be completed today.

**Comment by imAkshay26** [comment]
Todays task:
- [ ]  importing menu items from csv upload
- [ ]  test cases for controller functions

**Comment by imAkshay26** [comment]
In the case of csv file i have accessing csv records row by row as object of menu item.If there is a error in particular object then we should create another csv file and all invalid records should insert in that.

**Comment by SakshiParakh** [comment]
Test cases for import csv functinality are pending

**Comment by SakshiParakh** [comment]
Why is this story not complete yet? and where is your task for today ??

**Comment by imAkshay26** [comment]
mam, i am completing test cases of controller and for csv file..

**Comment by imAkshay26** [comment]
sorry.i forgot to write todays task.

**Comment by imAkshay26** [comment]
Todays target
- [ ]  controller test cases for terminal
- [ ]  test cases for csv

**Comment by imAkshay26** [comment]
mam there is small problem i have written import method for csv in terminal model.So that i should write validation on database. So i am going to change that method and write once again controller so that it can be tested in controller.and after that i am going to write test cases.This task will complete tomorrow.

**Comment by SakshiParakh** [comment]
Issue completed :ship:
